# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 12:31
from __future__ import unicode_literals

import NotAndBlog.models
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, max_length=3000, verbose_name='متن پیام')),
                ('date', django_jalali.db.models.jDateField(blank=True, default=None, null=True, verbose_name='تاریخ')),
                ('subject', models.CharField(default=None, max_length=72, verbose_name='موضوع')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=NotAndBlog.models.get_image_blog, verbose_name='عکس')),
                ('n_type', models.CharField(choices=[('p_i', ''), ('p_ha', ''), ('p_he', ''), ('r_ha', ''), ('r_he', ''), ('r_i', ''), ('n_ha_i', ''), ('n_ha_he', ''), ('n_i_ha', ''), ('n_i_he', ''), ('n_he_i', ''), ('n_he_ha', '')], default=None, max_length=10, verbose_name='گیرنده')),
                ('tag1', models.BooleanField(default=False, verbose_name='')),
                ('tag2', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
                ('helper', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Charity.HelperProfile', verbose_name='مددکار')),
                ('institute', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Charity.Institute', verbose_name='موسسه')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Charity.Project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name_plural': 'پیام ها',
                'verbose_name': 'پیام',
            },
        ),
    ]
