# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotAndBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tag3',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='tag4',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='tag5',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='tag6',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
    ]
