# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NotAndBlog', '0002_auto_20170413_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='institute',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Charity.Institute', verbose_name='موسسه'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='n_type',
            field=models.CharField(choices=[('p_i', ''), ('p_ha', ''), ('p_he', ''), ('r_ha', ''), ('r_he', 'گزارش مددکار'), ('r_i', ''), ('n_ha_i', ''), ('n_ha_he', ''), ('n_i_ha', ''), ('n_i_he', ''), ('n_he_i', ''), ('n_he_ha', '')], default=None, max_length=10, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Charity.Project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='متن پیام'),
        ),
    ]
