# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotAndBlog', '0003_auto_20170524_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='n_type',
            field=models.CharField(choices=[('p_i', ''), ('p_ha', ''), ('p_he', ''), ('r_ha', ''), ('r_he', 'گزارش مددکار توسط موسسه'), ('r_i', ''), ('n_ha_i', ''), ('n_ha_he', ''), ('n_i_ha', ''), ('n_i_he', ''), ('n_he_i', ''), ('n_he_ha', '')], default=None, max_length=10, verbose_name='نوع'),
        ),
    ]
