from django.conf.urls import include, url
from . import views, ajax, ajax_post

urlpatterns = [
    url(r'^helper_profile', 'Charity.views.helper_profile'),
    url(r'^institute$', 'Charity.views.institute'),
    url(r'^add_obj/(?P<this_id>\d+)/(?P<this_type>\w+)$', 'Charity.views.add_obj'),
    url(r'^add_project/(?P<this_id>\d+)$', 'Charity.views.add_project'),
    url(r'^add_case/(?P<this_id>\d+)$', 'Charity.views.add_case'),
    url(r'^add_institute$', 'Charity.views.add_institute'),
    url(r'^add_helper$', 'Charity.views.add_helper'),
    url(r'^project/(?P<this_id>\d+)', 'Charity.views.project'),
    url(r'^view_institute/(?P<this_id>\d+)', 'Charity.views.view_institute'),
    url(r'^view_helper/(?P<this_id>\d+)', 'Charity.views.view_helper'),
    # url(r'^pro_all/(?P<type_id>\w+)', 'Charity.views.pro_all'),
    url(r'^before_all_hip/(?P<query>\w+)/', 'Charity.views.before_all_hip'),
    url(r'^all_hip/(?P<query>\w+)/', 'Charity.views.pro_all'),
    url(r'^all_institute', 'Charity.views.all_institute'),
    url(r'^all_h_or_i/(?P<query>\w+)/', 'Charity.views.all_h_or_i'),
    url(r'^join_as$', 'Charity.views.join_as'),
    url(r'^what_you_want$', 'Charity.views.what_you_want'),
    url(r'^continue_fill$', 'Charity.views.continue_fill'),
    url(r'^ajax/pro_all__filter_for_test$', ajax.pro_all__filter_for_test, name='pro_all__filter_for_test'),
    url(r'^ajax/get__help_type$', ajax.get__help_type, name='get__help_type'),
    url(r'^ajax/get__city$', ajax.get__city, name='get__city'),
    url(r'^ajax/need_helper_test$', ajax.need_helper_test, name='need_helper_test'),
    url(r'^ajax/get_obj$', ajax.get_obj, name='get_obj'),
    url(r'^ajax/get_type_or_tooltip$', ajax.get_type_or_tooltip, name='get_tooltip_content'),
    url(r'^ajax/get_ins_pro$', ajax.get_ins_pro, name='get_ins_pro'),
    url(r'^ajax/get_p_mtms$', ajax.get_p_mtms, name='get_p_mtms'),
    url(r'^ajax/post/def_del$', ajax_post.def_del, name='get_ins_pro'),
    url(r'^ajax/post/fail_or_definite$', ajax_post.fail_or_definite, name='fail_or_definite'),
]
