# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 12:31
from __future__ import unicode_literals

import Charity.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(default=None, max_length=10, unique=True, verbose_name='کد ملی')),
                ('is_married', models.BooleanField(default=False, verbose_name='متاهل؟')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, default=None, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('m', 'آقا'), ('w', 'خانم')], default='m', max_length=6, null=True, verbose_name='جنسیت')),
                ('job', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='شغل')),
                ('explanation', models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='توضیحات')),
                ('tag1', models.BooleanField(default=False, verbose_name='')),
                ('tag2', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'مددجویان',
                'verbose_name': 'مددجو',
            },
        ),
        migrations.CreateModel(
            name='HelperProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('m', 'آقا'), ('w', 'خانم')], default='m', max_length=1, null=True, verbose_name='جنسیت')),
                ('birth_day', django_jalali.db.models.jDateField(blank=True, default=None, null=True, verbose_name='تاریخ تولد')),
                ('religion', models.CharField(blank=True, choices=[('sh', 'اسلام-شیعه'), ('so', 'اسلام-اهل سنت'), ('Ch', 'مسیحی'), ('j', 'یهودی'), ('o', 'سایر')], default='sh', max_length=3, null=True, verbose_name='دین-مذهب')),
                ('about_you', models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='درباره شما')),
                ('national_code', models.CharField(default=None, max_length=10, unique=True, verbose_name='کد ملی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=Charity.models.get_image_name, verbose_name='عکس')),
                ('is_married', models.BooleanField(default=False, verbose_name='متاهل؟')),
                ('address', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='آدرس')),
                ('phone_num', models.CharField(default=None, max_length=11, verbose_name='شماره تلفن همراه')),
                ('job', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='شغل')),
                ('monthly_cooperation_time', models.IntegerField(verbose_name='حد اقل زمان همکاری در ماه')),
                ('twitter', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='توییتر شما')),
                ('telegram', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='تلگرام شما')),
                ('facebook', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='فیس بوک شما')),
                ('instagram', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='اینستاگرام شما')),
                ('others_view_u', models.BooleanField(default=True, verbose_name='دیگران شما را ببینند؟')),
                ('in_home_page', models.BooleanField(default=False, verbose_name='')),
                ('tag2', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
                ('tag3', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
            ],
            options={
                'verbose_name_plural': ' پروفایل مددکاران',
                'verbose_name': 'پروفایل مددکار',
            },
        ),
        migrations.CreateModel(
            name='HelpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='عنوان')),
                ('father', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Charity.HelpType', verbose_name='ریشه')),
            ],
            options={
                'verbose_name_plural': 'انواع پروژه ها',
                'verbose_name': 'انواع پروژه',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='عنوان')),
                ('patent_num', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='شماره ثبت')),
                ('profile_image', models.ImageField(default=None, help_text='این عکس میتواند عکس موسسه یا هر چیز دیگری باشد.', upload_to=Charity.models.get_image_path, verbose_name='عکس')),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='آدرس')),
                ('establishment_date', django_jalali.db.models.jDateField(blank=True, default=None, null=True, verbose_name='تاریخ تاسیس')),
                ('site_address', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='آدرس سایت')),
                ('phone_num', models.CharField(default=None, max_length=11, verbose_name='شماره تلفن')),
                ('phone_num2', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='ایمیل')),
                ('post_code', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='کد پستی')),
                ('explanation', models.TextField(blank=True, default=None, help_text='شامل تاریخچه و اهداف', max_length=6000, null=True, verbose_name='توضیحات')),
                ('twitter', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='توییتر موسسه')),
                ('telegram', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='تلگرام موسسه')),
                ('facebook', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='فیس بوک موسسه')),
                ('instagram', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='اینستاگرام موسسه')),
                ('agent', models.CharField(default=None, help_text='این شخص رابط بین حاتم و موسسه مربوط میباشد.', max_length=72, verbose_name='نام و نام خانوادگی نماینده')),
                ('agent_job', models.CharField(default=None, help_text='این شخص رابط بین حاتم و موسسه مربوط میباشد.', max_length=72, verbose_name='جایگاه نمانده در موسسه')),
                ('agent_num', models.CharField(default=None, help_text='این شخص رابط بین حاتم و موسسه مربوط میباشد.', max_length=72, verbose_name='شماره همراه نماینده')),
                ('accepted', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('in_home_page', models.BooleanField(default=False, verbose_name='در صفحه ی اول باشد')),
                ('tag2', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
                ('tag3', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
                ('help_type1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute1', to='Charity.HelpType', verbose_name='نوع کمک رسانی')),
                ('help_type2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute2', to='Charity.HelpType', verbose_name='نوع کمک رسانی')),
                ('help_type3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute3', to='Charity.HelpType', verbose_name='نوع کمک رسانی')),
            ],
            options={
                'verbose_name_plural': 'موسسات',
                'verbose_name': 'موسسه',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=250, verbose_name='شهر')),
                ('location_father', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_child', to='Charity.Location', verbose_name='استان')),
            ],
            options={
                'verbose_name_plural': 'شهر ها',
                'verbose_name': 'شهر',
            },
        ),
        migrations.CreateModel(
            name='ManyToMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('definite', 'قطعی'), ('reserve', 'رزرو'), ('past', 'گذشته'), ('failed', 'رد شده'), ('a_f', 'مطلقا مردود')], default=None, max_length=10, verbose_name='وضعیت')),
                ('field', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='رشته')),
                ('level', models.CharField(blank=True, choices=[('bs', 'کارشناسی'), ('ms', 'کارشناسی ارشد'), ('phd', 'دکترا')], default=None, max_length=15, null=True, verbose_name='مقطع')),
                ('day', models.CharField(blank=True, choices=[('sa', 'شنبه'), ('su', 'یک شنبه'), ('m', 'دو شنبه'), ('tu', 'سه شنبه'), ('w', 'چهار شنبه'), ('th', 'پنج شنبه'), ('f', 'جمعه')], default=None, max_length=15, null=True, verbose_name='روز')),
                ('time_from', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='از ساعت')),
                ('time_to', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='تا ساعت')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=Charity.models.get_image__i_or_p, verbose_name='عکس')),
                ('tag1', models.BooleanField(default=False, verbose_name='')),
                ('tag2', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
                ('cities_wants_to_go', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_m_t_m', to='Charity.Location', verbose_name='شهر هایی که تمایل به رفتن دارید')),
                ('experience', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='h_experiences', to='Charity.HelpType', verbose_name='نوع کمک رسانی')),
                ('helper', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_many_to_many', to=settings.AUTH_USER_MODEL, verbose_name='مددکار')),
                ('institute', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Charity.Institute', verbose_name='موسسه')),
            ],
            options={
                'verbose_name_plural': '',
                'verbose_name': '',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='عنوان')),
                ('sentence', models.CharField(default=None, max_length=200, verbose_name='شعار پروژه')),
                ('start_date', django_jalali.db.models.jDateField(default=None, verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(default=None, verbose_name='تاریخ پایان')),
                ('min_person_hours', models.IntegerField(default=None, verbose_name='چند ساعت در هفته')),
                ('addressed', models.CharField(choices=[('w_ch', 'کودکان کار'), ('w_d', 'زنان بی سرپرست'), ('s_ch', 'کودکان بیمار'), ('e', 'محیط زیست'), ('an', 'حیوانات')], default=None, help_text='مخاطب پروژه شامل قشر و گروهی از مردم است که پروژه قرار است به آنها کمک کند', max_length=10, verbose_name='مخاطب پروژه')),
                ('age', models.CharField(blank=True, default=None, max_length=72, null=True, verbose_name='سن مورد نیاز')),
                ('gender', models.CharField(blank=True, choices=[('m', 'آقا'), ('w', 'خانم')], default=None, max_length=1, null=True, verbose_name='جنسیت')),
                ('n_t_experience', models.BooleanField(default=False, verbose_name='نیاز به تجربه قبلی؟')),
                ('status', models.CharField(blank=True, choices=[('p', 'ممکن'), ('i', 'ناممکن'), ('c', 'قطعی'), ('f', 'فوری'), ('fp', 'فوری ممکن'), ('fi', 'فوری ناممکن'), ('ipt', 'مهم')], default=None, max_length=10, null=True, verbose_name='وضعیت')),
                ('from_home', models.BooleanField(default=False, verbose_name='از خانه؟')),
                ('accommodation', models.BooleanField(default=False, verbose_name='محل اقامت؟')),
                ('explanation', models.TextField(blank=True, default=None, max_length=6000, null=True, verbose_name='توضیحات پروژه')),
                ('in_home_page', models.BooleanField(default=False, verbose_name='')),
                ('tag4', models.BooleanField(default=False, verbose_name='')),
                ('tag2', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
                ('tag3', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='')),
                ('case', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Charity.Case', verbose_name='مددجو')),
                ('help_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Charity.HelpType', verbose_name='نوع کمک رسانی')),
                ('institute', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Charity.Institute', verbose_name='موسسه تعریف کننده')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Charity.Location', verbose_name='شهر')),
            ],
            options={
                'verbose_name_plural': 'پروژه های کمک رسانی',
                'verbose_name': 'پروژه کمک رسانی',
            },
        ),
        migrations.AddField(
            model_name='manytomany',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_many_to_many', to='Charity.Project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='manytomany',
            name='skill',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_m_t_m', to='Charity.HelpType', verbose_name='مهارتها'),
        ),
        migrations.AddField(
            model_name='institute',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='Charity.Location', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Charity.Location', verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='case',
            name='institute',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='Charity.Institute', verbose_name='موسسه حمایت کننده'),
        ),
    ]
