# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0002_helptype_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptype',
            name='tag',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='location',
            name='tag',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='location',
            name='type_type',
            field=models.CharField(blank=True, choices=[('sh', ''), ('so', ''), ('Ch', ''), ('j', ''), ('o', '')], default='sh', max_length=3, null=True, verbose_name='نوع'),
        ),
    ]
