# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0003_auto_20170314_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manytomany',
            name='experience',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_experiences', to='Charity.HelpType', verbose_name='تجربه های داوطلبانه'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_many_to_many', to='Charity.Project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='status',
            field=models.CharField(blank=True, choices=[('definite', 'قطعی'), ('reserve', 'رزرو'), ('past', 'گذشته'), ('failed', 'رد شده'), ('a_f', 'مطلقا مردود')], default=None, max_length=10, null=True, verbose_name='وضعیت'),
        ),
    ]
