# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0004_auto_20170314_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='min_person_hours',
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='tag1',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tag1',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
