# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0005_auto_20170314_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tag1',
            new_name='immediate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='age',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tag2',
        ),
        migrations.AddField(
            model_name='project',
            name='max_age',
            field=models.IntegerField(blank=True, default=None, max_length=72, null=True, verbose_name='سن مورد نیاز'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_age',
            field=models.IntegerField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='addressed',
            field=models.CharField(choices=[('o', 'سایر'), ('w_ch', 'کودکان کار'), ('w_d', 'زنان بی سرپرست'), ('s_ch', 'کودکان بیمار'), ('e', 'محیط زیست'), ('an', 'حیوانات')], default=None, help_text='مخاطب پروژه شامل قشر و گروهی از مردم است که پروژه قرار است به آنها کمک کند', max_length=10, verbose_name='مخاطب پروژه'),
        ),
    ]
