# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 12:52
from __future__ import unicode_literals

import Charity.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0006_auto_20170315_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='birth_date',
            new_name='tag8',
        ),
        migrations.RenameField(
            model_name='helptype',
            old_name='tag',
            new_name='tag1',
        ),
        migrations.RenameField(
            model_name='institute',
            old_name='tag2',
            new_name='tag4',
        ),
        migrations.RenameField(
            model_name='manytomany',
            old_name='tag1',
            new_name='tag3',
        ),
        migrations.RenameField(
            model_name='manytomany',
            old_name='tag2',
            new_name='tag5',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tag3',
            new_name='tag5',
        ),
        migrations.RemoveField(
            model_name='helperprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_father',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='case',
            name='tag3',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='case',
            name='tag4',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='case',
            name='tag5',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='case',
            name='tag6',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='lng'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='tag4',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='tag5',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='tag6',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='helptype',
            name='tag2',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='helptype',
            name='tag3',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='helptype',
            name='tag4',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='institute',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='institute',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='lng'),
        ),
        migrations.AddField(
            model_name='institute',
            name='n_score',
            field=models.IntegerField(blank=True, default=None, max_length=20, null=True, verbose_name='امتیاز منفی'),
        ),
        migrations.AddField(
            model_name='institute',
            name='tag1',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='institute',
            name='tag5',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='institute',
            name='tag6',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='location',
            name='father',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Charity.Location', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='lng'),
        ),
        migrations.AddField(
            model_name='manytomany',
            name='mtm_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('time', 'time'), ('skill', 'skill'), ('p_mtm', 'p_mtm')], default=None, max_length=20, null=True, verbose_name='برچسب نوع'),
        ),
        migrations.AddField(
            model_name='manytomany',
            name='self_or_hm',
            field=models.BooleanField(default=False, verbose_name='اگر درست پس حاتم نتیجه گرفته.'),
        ),
        migrations.AddField(
            model_name='manytomany',
            name='tag4',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='manytomany',
            name='tag6',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to=Charity.models.get_image_path, verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='project',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='project',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='lng'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag1',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tag2',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tag6',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tag7',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tag8',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='helperprofile',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Charity.models.get_image_name, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='agent_num',
            field=models.CharField(default=None, help_text='این شخص رابط بین حاتم و موسسه مربوط میباشد.', max_length=11, verbose_name='شماره همراه نماینده'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(help_text='این عکس میتواند عکس موسسه یا هر چیز دیگری باشد.', upload_to=Charity.models.get_image_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default=None, max_length=250, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='cities_wants_to_go',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtms', to='Charity.Location', verbose_name='شهر هایی که تمایل به رفتن دارید'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='experience',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtms', to='Charity.HelpType', verbose_name='تجربه های داوطلبانه'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='helper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtms', to=settings.AUTH_USER_MODEL, verbose_name='مددکار'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to=Charity.models.get_image__i_or_p, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='institute',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtms', to='Charity.Institute', verbose_name='موسسه'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtms', to='Charity.Project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='skill',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_mtms', to='Charity.HelpType', verbose_name='مهارتها'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='time_from',
            field=models.TimeField(blank=True, default=None, max_length=15, null=True, verbose_name='از ساعت'),
        ),
        migrations.AlterField(
            model_name='manytomany',
            name='time_to',
            field=models.TimeField(blank=True, default=None, max_length=15, null=True, verbose_name='تا ساعت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, default=None, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='project',
            name='immediate',
            field=models.BooleanField(default=False, verbose_name='در صورت نیاز فوری علامت بزنید. لطفا تا حد امکان از این کار خودداری کنید.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='بیشترین سن ممکن برای خیر خواه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='min_age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='کمترین سن ممکن برای خیر خواه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sentence',
            field=models.CharField(default=None, max_length=200, verbose_name='پروژه در جمله'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, default=None, null=True, verbose_name='تاریخ شروع'),
        ),
    ]
