# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 00:28
from __future__ import unicode_literals

import Charity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0007_auto_20170510_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tag1',
            new_name='accepted',
        ),
        migrations.AddField(
            model_name='helptype',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=Charity.models.get_image_help_type),
        ),
    ]
