# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0008_auto_20170522_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'ممکن'), ('i', 'ناممکن'), ('c', 'قطعی'), ('s', 'موفق'), ('fp', 'فوری ممکن'), ('fi', 'فوری ناممکن'), ('ipt', 'مهم')], default=None, max_length=10, null=True, verbose_name='وضعیت'),
        ),
    ]
