# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 00:52
from __future__ import unicode_literals

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0009_auto_20170522_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='manytomany',
            name='the_date',
            field=django_jalali.db.models.jDateField(blank=True, default=None, null=True, verbose_name='تاریخ'),
        ),
    ]
