# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0010_manytomany_the_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='تایید شده؟'),
        ),
    ]
